spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wydad
    username: GreenPulse
    password:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
  server:
    port: 8089
  jpa:
    properties:
      hibernate:
        default_schema: public